# Generated by Django 2.2 on 2021-02-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0006_remove_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
