# Generated by Django 2.2 on 2021-02-17 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0007_course_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='Description',
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='courses_app.Description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=45),
        ),
    ]
