# Generated by Django 2.2 on 2021-02-26 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210226_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wall_post',
            old_name='post_txt',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='wall_post',
            old_name='post_author',
            new_name='poster',
        ),
    ]
