# Generated by Django 3.1.7 on 2021-03-15 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kick', models.CharField(max_length=255)),
                ('snare', models.CharField(max_length=255)),
                ('HHcl', models.CharField(max_length=255)),
                ('HHop', models.CharField(max_length=255)),
                ('crash', models.CharField(max_length=255)),
                ('ride', models.CharField(max_length=255)),
                ('tom_h', models.CharField(max_length=255)),
                ('tom_m', models.CharField(max_length=255)),
                ('tom_l', models.CharField(max_length=255)),
                ('perc', models.CharField(max_length=255)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_kits', to='home.user')),
                ('favorited_by', models.ManyToManyField(related_name='favorited_kits', to='home.User')),
            ],
        ),
    ]
