# Generated by Django 2.2 on 2021-02-27 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='joined_trips',
            new_name='trip_attendees',
        ),
    ]
